---
title: "Hearthstone competitive format: Nash equlibrium perspective"
author: "Samvel Avakian"
date: 'July 2019'
output: pdf_document
urlcolor: blue
indent: true
header-includes:
   - \usepackage{amsmath}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Specialist format

Specialist format is used in official Hearthstone (Blizzard's hit collectible card game) competitions. Here's how it works:

* Both players create a set of three decks of 30 cards: primary, secondary and tertiary
    + Secondary and tertiary decks have to share no less than 25 cards with the primary deck
* In the first game of the match both players have to use their primary deck
* Starting from game two players can secretly pick any deck, no matter the result of prior games
* Matches are best-of-3 or best-of-5, although most matches are best-of-3

Since players may randomize their deck choice (random.org have always been a key resource for competitive Hearthstone players), one is tempted to find a Nash equilibrium in mixed strategies based on a matrix of winrates (how Hero's decks match up against Opponent's ones). Let's establish some terms useful for such analysis.

Let $w_{ij}$ be Hero's $i$-ry deck's expected winrate against Opponent's $j$-ry deck, and $W$ be a matrix representation of these winrates:
$$W = 
\begin{pmatrix}
w_{1,1} & w_{1,2} & w_{1,3}\\
w_{2,1} & w_{2,2} & w_{2,3}\\
w_{3,1} & w_{3,2} & w_{3,3}
\end{pmatrix}.$$

Let $m_{kl}(S)$ be Hero's expected _match_ winrate, where $k$ and $l$ are Hero's and Opponent's match scores respectively and $S$ is a strategy profile with respect to deck choices. Let $M(S)$ be a matrix representation of these winrates. Then for a best of 3 ($S$ references are omitted for clarity)
$$M = 
\begin{pmatrix}
m_{0,0} & m_{0,1}\\
m_{1,0} & m_{1,1}
\end{pmatrix},$$ and for best of n
$$M = 
\begin{pmatrix}
    m_{0,0} & m_{0,1} & m_{0,2} & \dots  & m_{0,n-1} \\
    m_{1,0} & m_{1,1} & m_{1,2} & \dots  & m_{1,n-1} \\
    \vdots & \vdots & \vdots & \ddots & \vdots \\
    m_{n-1,0} & m_{n-1,} & m_{n-1,2} & \dots  & m_{n-1,n-1}
\end{pmatrix}.$$

Now, let's compute $M(S^*)$, where $S^*$ is Nash equilibrium in mixed strategies for the best-of-N case. Note that every game after the first one is generated by the same choice of decks, and the first one is played with primary decks. This recurring subgame is a zero-sum game represented by payoff matrix $W$. It is obvious that 
$$m_{n-1,n-1} = V(W),$$
where V is value of the game. It is also easy to show that the match (disregarding the game one for now) has a binomial nature - if the match score is $i$ - $j$, Hero has to succeed in $n-i$ trials of $2n-1-i-j$ remaining to win. Also note that 
$$m_{0,0} = w_{11}m_{1,0}+(1 - w_{11})m_{0,1}$$
It then follows that 
$$ m_{i,j} = \left\{
        \begin{array}{ll}
            w_{11}m_{1,0}+(1 - w_{11})m_{0,1}, & \quad \text{if } i = j = 0\\
            \sum_{k=n-i}^{2n-1-i-j} {2n-1-i-j\choose k}V^{k}(W)(1-V(W))^{2n-1-i-j-k},  & \quad \text{otherwise}\\
        \end{array}
    \right.$$
    
Thus, Hero's winrate for the match itself is 
$$
\begin{gathered}
m_{0,0} = w_{11}m_{1,0}+(1 - w_{11})m_{0,1} =  \\
=w_{11}\sum_{k=n-1}^{2n-2} {2n-2\choose k}V^{k}(W)(1-V(W))^{2n-2-k}+(1-w_{11})\sum_{k=n}^{2n-2} {2n-2\choose k}V^{k}(W)(1-V(W))^{2n-2-k}
\end{gathered}
$$

It is easy to show that $V(W)$ is the solution of a simple linear programming problem that also produces Nash equilibrium strategy profiles (see any game theory textbook, e.g. Owen, 1968):
$$V(W) = \max_{S} \lambda$$ 
where

$$S = \begin{cases}
w_{1,1}x_1 + w_{2,1}x_2 + w_{3,1}x_3 \geq \lambda \\
w_{1,2}x_1 + w_{2,2}x_2 + w_{3,2}x_3 \geq \lambda \\
w_{1,3}x_1 + w_{2,3}x_2 + w_{3,3}x_3 \geq \lambda \\ 
x_1 + x_2 + x_3 = 1 \\
x_1,x_2,x_3 \geq 0
\end{cases}$$
where $x_i$ is the optimal probability of choosing $i$-ry deck for Hero. The intuition here is that if, given Hero's _supposed_ equilibrium strategy, there is an Opponent strategy that generates Hero's winrate lower than the resulting value of the game under this _supposed_ equilibrium, it is beneficial for the Opponent to deviate and switch to that strategy, and thus Hero's strategy isn't equilibrial. 

# Conclusion

In this paper I show that expected match winrate given deck winrates is a lot easier to compute for Specialist format than for formats with variable sets of available decks (e.g. Last Hero Standing, Conquest). An interactive Shiny app for calculating match winrates (and more) is available at [my website](https://naturewillconfess.com/specialist/).